version: '3.8'

services:
  rates_postgres:
    image: mirror.gcr.io/postgres:16-alpine
    container_name: rates_backend_db
    environment:
      POSTGRES_USER: rates_admin
      POSTGRES_PASSWORD: rates_secure_pass
      POSTGRES_DB: rates_db 
    ports:
      - "5432:5432"
    volumes:
      - rates_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  rates_pgdata: