version: '3'

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    environment:
      DOCKER_API_VERSION: "1.40"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=ketlukashenko@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

  frontend:
    image: ghcr.io/t-group1/stock-exchange/frontend:latest
    container_name: frontend
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`team1.verstack.ru`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

  backend:
    image: ghcr.io/t-group1/stock-exchange/backend:latest
    container_name: backend
    restart: always
    environment:
      DB_HOST: "212.8.228.70"
      DB_PORT: "5432"
      DB_USER: "team1"
      DB_PASSWORD: "7LA4B1ud1p0g5sFbivb0"
      DB_NAME: "event"
      DB_SSLMODE: "require"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`team1.verstack.ru`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
      - "traefik.http.middlewares.strip-api.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.middlewares=strip-api"