FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go mod tidy
RUN go build -o main-server ./...

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/main-server .

EXPOSE 8080
CMD ["./main-server"]