// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: currencies.sql

package db

import (
	"context"
)

const createCurrency = `-- name: CreateCurrency :one
INSERT INTO currencies (code, name, nominal)
VALUES ($1, $2, $3)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  nominal = EXCLUDED.nominal
RETURNING code, name, nominal
`

type CreateCurrencyParams struct {
	Code    string `json:"code"`
	Name    string `json:"name"`
	Nominal int32  `json:"nominal"`
}

func (q *Queries) CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error) {
	row := q.db.QueryRow(ctx, createCurrency, arg.Code, arg.Name, arg.Nominal)
	var i Currency
	err := row.Scan(&i.Code, &i.Name, &i.Nominal)
	return i, err
}

const getCurrencies = `-- name: GetCurrencies :many
SELECT code, name, nominal FROM currencies
ORDER BY code
`

func (q *Queries) GetCurrencies(ctx context.Context) ([]Currency, error) {
	rows, err := q.db.Query(ctx, getCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Currency{}
	for rows.Next() {
		var i Currency
		if err := rows.Scan(&i.Code, &i.Name, &i.Nominal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCurrencyByCode = `-- name: GetCurrencyByCode :one
SELECT code, name, nominal FROM currencies
WHERE code = $1
`

func (q *Queries) GetCurrencyByCode(ctx context.Context, code string) (Currency, error) {
	row := q.db.QueryRow(ctx, getCurrencyByCode, code)
	var i Currency
	err := row.Scan(&i.Code, &i.Name, &i.Nominal)
	return i, err
}
