// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO favorites (user_id, currency_pair)
VALUES ($1, $2)
ON CONFLICT (user_id, currency_pair) DO NOTHING
`

type AddFavoriteParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	CurrencyPair string      `json:"currency_pair"`
}

// Добавление валютной пары в избранное.
// ON CONFLICT DO NOTHING гарантирует, что при повторном вызове не будет ошибки 500.
func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.CurrencyPair)
	return err
}

const getUserFavoritePairs = `-- name: GetUserFavoritePairs :many
SELECT currency_pair
FROM favorites
WHERE user_id = $1
`

// Получение только валютных пар (удобно, если в API нужно просто проверить, что пара в избранном)
func (q *Queries) GetUserFavoritePairs(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserFavoritePairs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var currency_pair string
		if err := rows.Scan(&currency_pair); err != nil {
			return nil, err
		}
		items = append(items, currency_pair)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFavorites = `-- name: GetUserFavorites :many
SELECT currency_pair
FROM favorites
WHERE user_id = $1
ORDER BY created_at DESC
`

// Получение полного списка избранных валютных пар
func (q *Queries) GetUserFavorites(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserFavorites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var currency_pair string
		if err := rows.Scan(&currency_pair); err != nil {
			return nil, err
		}
		items = append(items, currency_pair)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites
WHERE user_id = $1 AND currency_pair = $2
`

type RemoveFavoriteParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	CurrencyPair string      `json:"currency_pair"`
}

// Удаление валютной пары из избранного
func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.CurrencyPair)
	return err
}
