// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO favorites (user_id, currency_code)
VALUES ($1, $2)
ON CONFLICT (user_id, currency_code) DO NOTHING
`

type AddFavoriteParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	CurrencyCode string      `json:"currency_code"`
}

// Добавление валюты в избранное.
// ON CONFLICT DO NOTHING гарантирует, что при повторном вызове не будет ошибки 500.
func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.CurrencyCode)
	return err
}

const getUserFavoriteCodes = `-- name: GetUserFavoriteCodes :many
SELECT currency_code 
FROM favorites 
WHERE user_id = $1
`

// Получение только кодов (удобно, если в API нужно просто проверить, что валюта в избранном)
func (q *Queries) GetUserFavoriteCodes(ctx context.Context, userID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserFavoriteCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var currency_code string
		if err := rows.Scan(&currency_code); err != nil {
			return nil, err
		}
		items = append(items, currency_code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFavorites = `-- name: GetUserFavorites :many
SELECT c.code, c.name, c.nominal
FROM favorites f
JOIN currencies c ON f.currency_code = c.code
WHERE f.user_id = $1
ORDER BY f.created_at DESC
`

// Получение полного списка избранных валют с их названиями (для красивого JSON в API)
func (q *Queries) GetUserFavorites(ctx context.Context, userID pgtype.UUID) ([]Currency, error) {
	rows, err := q.db.Query(ctx, getUserFavorites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Currency{}
	for rows.Next() {
		var i Currency
		if err := rows.Scan(&i.Code, &i.Name, &i.Nominal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites
WHERE user_id = $1 AND currency_code = $2
`

type RemoveFavoriteParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	CurrencyCode string      `json:"currency_code"`
}

// Удаление валюты из избранного
func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.CurrencyCode)
	return err
}
