// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Currency struct {
	Code    string `json:"code"`
	Name    string `json:"name"`
	Nominal int32  `json:"nominal"`
}

type CurrencyRate struct {
	ID               int64         `json:"id"`
	CurrencyCode     string        `json:"currency_code"`
	Rate             pgtype.Numeric `json:"rate"`
	RateDate         pgtype.Date   `json:"rate_date"`
	Source           string        `json:"source"`
	ChangePercentage pgtype.Numeric `json:"change_percentage"`
}

type Notification struct {
	ID             pgtype.UUID `json:"id"`
	UserID         pgtype.UUID `json:"user_id"`
	SubscriptionID pgtype.UUID `json:"subscription_id"`
	Type           string      `json:"type"`
	Title          string      `json:"title"`
	Message        string      `json:"message"`
	IsRead         pgtype.Bool `json:"is_read"`
	CreatedAt      int64       `json:"created_at"`
}

type NotificationSetting struct {
	UserID         pgtype.UUID `json:"user_id"`
	EmailEnabled   pgtype.Bool `json:"email_enabled"`
	BrowserEnabled pgtype.Bool `json:"browser_enabled"`
	QuietHoursStart pgtype.Text `json:"quiet_hours_start"`
	QuietHoursEnd   pgtype.Text `json:"quiet_hours_end"`
}

type Subscription struct {
	ID           pgtype.UUID    `json:"id"`
	UserID       pgtype.UUID    `json:"user_id"`
	CurrencyCode string         `json:"currency_code"`
	RateValue    pgtype.Numeric `json:"rate_value"`
	Condition    string         `json:"condition"`
	IsActive     pgtype.Bool    `json:"is_active"`
	CreatedAt    int64          `json:"created_at"`
	TriggeredAt  pgtype.Int8    `json:"triggered_at"`
}

type User struct {
	ID                       pgtype.UUID `json:"id"`
	Email                    string      `json:"email"`
	Name                     string      `json:"name"`
	PasswordHash             string      `json:"password_hash"`
	IsVerified               pgtype.Bool `json:"is_verified"`
	VerificationToken        pgtype.Text `json:"verification_token"`
	VerificationTokenExpires pgtype.Int8 `json:"verification_token_expires"`
	CreatedAt                int64       `json:"created_at"`
}