// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getNotificationSettings = `-- name: GetNotificationSettings :one
SELECT user_id, email_enabled, browser_enabled, quiet_hours_start, quiet_hours_end FROM notification_settings
WHERE user_id = $1
`

func (q *Queries) GetNotificationSettings(ctx context.Context, userID pgtype.UUID) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, getNotificationSettings, userID)
	var i NotificationSetting
	err := row.Scan(
		&i.UserID,
		&i.EmailEnabled,
		&i.BrowserEnabled,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
	)
	return i, err
}

const upsertNotificationSettings = `-- name: UpsertNotificationSettings :one
INSERT INTO notification_settings (user_id, email_enabled, browser_enabled, quiet_hours_start, quiet_hours_end)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE SET
  email_enabled = EXCLUDED.email_enabled,
  browser_enabled = EXCLUDED.browser_enabled,
  quiet_hours_start = EXCLUDED.quiet_hours_start,
  quiet_hours_end = EXCLUDED.quiet_hours_end
RETURNING user_id, email_enabled, browser_enabled, quiet_hours_start, quiet_hours_end
`

type UpsertNotificationSettingsParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	EmailEnabled    pgtype.Bool `json:"email_enabled"`
	BrowserEnabled  pgtype.Bool `json:"browser_enabled"`
	QuietHoursStart pgtype.Text `json:"quiet_hours_start"`
	QuietHoursEnd   pgtype.Text `json:"quiet_hours_end"`
}

func (q *Queries) UpsertNotificationSettings(ctx context.Context, arg UpsertNotificationSettingsParams) (NotificationSetting, error) {
	row := q.db.QueryRow(ctx, upsertNotificationSettings,
		arg.UserID,
		arg.EmailEnabled,
		arg.BrowserEnabled,
		arg.QuietHoursStart,
		arg.QuietHoursEnd,
	)
	var i NotificationSetting
	err := row.Scan(
		&i.UserID,
		&i.EmailEnabled,
		&i.BrowserEnabled,
		&i.QuietHoursStart,
		&i.QuietHoursEnd,
	)
	return i, err
}
