// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateRate(ctx context.Context, arg CreateRateParams) (CurrencyRate, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateSubscription(ctx context.Context, arg DeactivateSubscriptionParams) error
	GetActiveSubscriptionsForCurrency(ctx context.Context, currencyCode string) ([]Subscription, error)
	GetCurrencies(ctx context.Context) ([]Currency, error)
	GetCurrencyByCode(ctx context.Context, code string) (Currency, error)
	GetLatestRates(ctx context.Context) ([]CurrencyRate, error)
	GetNotificationSettings(ctx context.Context, userID pgtype.UUID) (NotificationSetting, error)
	GetRateHistory(ctx context.Context, arg GetRateHistoryParams) ([]GetRateHistoryRow, error)
	GetRatesByDate(ctx context.Context, rateDate pgtype.Date) ([]CurrencyRate, error)
	GetSubscriptionByID(ctx context.Context, id pgtype.UUID) (Subscription, error)
	GetUnreadCount(ctx context.Context, userID pgtype.UUID) (int64, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByVerificationToken(ctx context.Context, arg GetUserByVerificationTokenParams) (User, error)
	GetUserNotifications(ctx context.Context, arg GetUserNotificationsParams) ([]Notification, error)
	GetUserSubscriptions(ctx context.Context, userID pgtype.UUID) ([]Subscription, error)
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) error
	UpsertNotificationSettings(ctx context.Context, arg UpsertNotificationSettingsParams) (NotificationSetting, error)
	VerifyUser(ctx context.Context, arg VerifyUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)