// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (user_id, currency_code, rate_value, condition)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, currency_code, rate_value, condition, is_active, created_at, triggered_at
`

type CreateSubscriptionParams struct {
	UserID       pgtype.UUID    `json:"user_id"`
	CurrencyCode string         `json:"currency_code"`
	RateValue    pgtype.Numeric `json:"rate_value"`
	Condition    string         `json:"condition"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.CurrencyCode,
		arg.RateValue,
		arg.Condition,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrencyCode,
		&i.RateValue,
		&i.Condition,
		&i.IsActive,
		&i.CreatedAt,
		&i.TriggeredAt,
	)
	return i, err
}

const deactivateSubscription = `-- name: DeactivateSubscription :exec
UPDATE subscriptions
SET is_active = false, triggered_at = $2
WHERE id = $1
`

type DeactivateSubscriptionParams struct {
	ID          pgtype.UUID `json:"id"`
	TriggeredAt pgtype.Int8 `json:"triggered_at"`
}

func (q *Queries) DeactivateSubscription(ctx context.Context, arg DeactivateSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deactivateSubscription, arg.ID, arg.TriggeredAt)
	return err
}

const getActiveSubscriptions = `-- name: GetActiveSubscriptions :many
SELECT id, user_id, currency_code, rate_value, condition, is_active, created_at, triggered_at FROM subscriptions
WHERE is_active = true
`

func (q *Queries) GetActiveSubscriptions(ctx context.Context) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, getActiveSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CurrencyCode,
			&i.RateValue,
			&i.Condition,
			&i.IsActive,
			&i.CreatedAt,
			&i.TriggeredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveSubscriptionsForCurrency = `-- name: GetActiveSubscriptionsForCurrency :many
SELECT id, user_id, currency_code, rate_value, condition, is_active, created_at, triggered_at FROM subscriptions
WHERE currency_code = $1 AND is_active = true
`

func (q *Queries) GetActiveSubscriptionsForCurrency(ctx context.Context, currencyCode string) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, getActiveSubscriptionsForCurrency, currencyCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CurrencyCode,
			&i.RateValue,
			&i.Condition,
			&i.IsActive,
			&i.CreatedAt,
			&i.TriggeredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, user_id, currency_code, rate_value, condition, is_active, created_at, triggered_at FROM subscriptions
WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id pgtype.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CurrencyCode,
		&i.RateValue,
		&i.Condition,
		&i.IsActive,
		&i.CreatedAt,
		&i.TriggeredAt,
	)
	return i, err
}

const getUserSubscriptions = `-- name: GetUserSubscriptions :many
SELECT id, user_id, currency_code, rate_value, condition, is_active, created_at, triggered_at FROM subscriptions
WHERE user_id = $1
`

func (q *Queries) GetUserSubscriptions(ctx context.Context, userID pgtype.UUID) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, getUserSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CurrencyCode,
			&i.RateValue,
			&i.Condition,
			&i.IsActive,
			&i.CreatedAt,
			&i.TriggeredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
