// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash, is_verified, verification_token, verification_token_expires)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, name, password_hash, is_verified, verification_token, verification_token_expires, created_at
`

type CreateUserParams struct {
	Email                    string      `json:"email"`
	Name                     string      `json:"name"`
	PasswordHash             string      `json:"password_hash"`
	IsVerified               pgtype.Bool `json:"is_verified"`
	VerificationToken        pgtype.Text `json:"verification_token"`
	VerificationTokenExpires pgtype.Int8 `json:"verification_token_expires"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.IsVerified,
		arg.VerificationToken,
		arg.VerificationTokenExpires,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpires,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, is_verified, verification_token, verification_token_expires, created_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpires,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, is_verified, verification_token, verification_token_expires, created_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpires,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByVerificationToken = `-- name: GetUserByVerificationToken :one
SELECT id, email, name, password_hash, is_verified, verification_token, verification_token_expires, created_at FROM users
WHERE verification_token = $1 AND verification_token_expires > $2
`

func (q *Queries) GetUserByVerificationToken(ctx context.Context, arg GetUserByVerificationTokenParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByVerificationToken, arg.VerificationToken, arg.VerificationTokenExpires)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpires,
		&i.CreatedAt,
	)
	return i, err
}

const verifyUser = `-- name: VerifyUser :one
UPDATE users
SET is_verified = true,
    verification_token = NULL,
    verification_token_expires = NULL
WHERE verification_token = $1 AND verification_token_expires > $2
RETURNING id, email, name, password_hash, is_verified, verification_token, verification_token_expires, created_at
`

type VerifyUserParams struct {
	VerificationToken        string `json:"verification_token"`
	VerificationTokenExpires int64  `json:"verification_token_expires"`
}

func (q *Queries) VerifyUser(ctx context.Context, arg VerifyUserParams) (User, error) {
	row := q.db.QueryRow(ctx, verifyUser, arg.VerificationToken, arg.VerificationTokenExpires)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsVerified,
		&i.VerificationToken,
		&i.VerificationTokenExpires,
		&i.CreatedAt,
	)
	return i, err
}

type GetUserByVerificationTokenParams struct {
	VerificationToken        string `json:"verification_token"`
	VerificationTokenExpires int64  `json:"verification_token_expires"`
}