// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO favorites (user_id, base_currency, quote_currency)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, base_currency, quote_currency) DO NOTHING
`

type AddFavoriteParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	BaseCurrency  string      `json:"base_currency"`
	QuoteCurrency string      `json:"quote_currency"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.BaseCurrency, arg.QuoteCurrency)
	return err
}

const getUserFavorites = `-- name: GetUserFavorites :many
SELECT base_currency, quote_currency, created_at
FROM favorites
WHERE user_id = $1
ORDER BY created_at DESC
`

type GetUserFavoritesRow struct {
	BaseCurrency  string `json:"base_currency"`
	QuoteCurrency string `json:"quote_currency"`
	CreatedAt     int64  `json:"created_at"`
}

func (q *Queries) GetUserFavorites(ctx context.Context, userID pgtype.UUID) ([]GetUserFavoritesRow, error) {
	rows, err := q.db.Query(ctx, getUserFavorites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserFavoritesRow{}
	for rows.Next() {
		var i GetUserFavoritesRow
		if err := rows.Scan(&i.BaseCurrency, &i.QuoteCurrency, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isFavorite = `-- name: IsFavorite :one
SELECT EXISTS (
    SELECT 1 FROM favorites 
    WHERE user_id = $1 
      AND base_currency = $2 
      AND quote_currency = $3
)
`

type IsFavoriteParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	BaseCurrency  string      `json:"base_currency"`
	QuoteCurrency string      `json:"quote_currency"`
}

func (q *Queries) IsFavorite(ctx context.Context, arg IsFavoriteParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFavorite, arg.UserID, arg.BaseCurrency, arg.QuoteCurrency)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites
WHERE user_id = $1 
  AND base_currency = $2 
  AND quote_currency = $3
`

type RemoveFavoriteParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	BaseCurrency  string      `json:"base_currency"`
	QuoteCurrency string      `json:"quote_currency"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.BaseCurrency, arg.QuoteCurrency)
	return err
}
