// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AlertRule struct {
	ID            int64
	UserID        int64
	CurrencyCode  *string
	TargetRate    pgtype.Numeric
	ConditionType string
	IsActive      *bool
}

type Currency struct {
	Code string
	Name string
}

type CurrencyRate struct {
	ID           int64
	CurrencyCode *string
	Rate         pgtype.Numeric
	RateDate     pgtype.Date
}
