// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rates.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlertRule = `-- name: CreateAlertRule :exec
INSERT INTO alert_rules (user_id, currency_code, target_rate, condition_type)
VALUES ($1, $2, $3, $4)
`

type CreateAlertRuleParams struct {
	UserID        int64
	CurrencyCode  string
	TargetRate    pgtype.Numeric
	ConditionType string
}

func (q *Queries) CreateAlertRule(ctx context.Context, arg CreateAlertRuleParams) error {
	_, err := q.db.Exec(ctx, createAlertRule,
		arg.UserID,
		arg.CurrencyCode,
		arg.TargetRate,
		arg.ConditionType,
	)
	return err
}

const getActiveAlertRules = `-- name: GetActiveAlertRules :many
SELECT id, user_id, currency_code, target_rate, condition_type 
FROM alert_rules 
WHERE is_active = true
`

type GetActiveAlertRulesRow struct {
	ID            int64
	UserID        int64
	CurrencyCode  string
	TargetRate    pgtype.Numeric
	ConditionType string
}

func (q *Queries) GetActiveAlertRules(ctx context.Context) ([]GetActiveAlertRulesRow, error) {
	rows, err := q.db.Query(ctx, getActiveAlertRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveAlertRulesRow
	for rows.Next() {
		var i GetActiveAlertRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CurrencyCode,
			&i.TargetRate,
			&i.ConditionType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestRates = `-- name: GetLatestRates :many
SELECT DISTINCT ON (currency_code) currency_code, rate, rate_date
FROM currency_rates
ORDER BY currency_code, rate_date DESC
`

type GetLatestRatesRow struct {
	CurrencyCode string
	Rate         pgtype.Numeric
	RateDate     time.Time
}

func (q *Queries) GetLatestRates(ctx context.Context) ([]GetLatestRatesRow, error) {
	rows, err := q.db.Query(ctx, getLatestRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestRatesRow
	for rows.Next() {
		var i GetLatestRatesRow
		if err := rows.Scan(&i.CurrencyCode, &i.Rate, &i.RateDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRatesHistory = `-- name: GetRatesHistory :many
SELECT rate, rate_date 
FROM currency_rates
WHERE currency_code = $1
ORDER BY rate_date ASC
`

type GetRatesHistoryRow struct {
	Rate     pgtype.Numeric
	RateDate time.Time
}

func (q *Queries) GetRatesHistory(ctx context.Context, currencyCode string) ([]GetRatesHistoryRow, error) {
	rows, err := q.db.Query(ctx, getRatesHistory, currencyCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRatesHistoryRow
	for rows.Next() {
		var i GetRatesHistoryRow
		if err := rows.Scan(&i.Rate, &i.RateDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCurrency = `-- name: InsertCurrency :exec
INSERT INTO currencies (code, name)
VALUES ($1, $2)
ON CONFLICT (code) DO NOTHING
`

type InsertCurrencyParams struct {
	Code string
	Name string
}

func (q *Queries) InsertCurrency(ctx context.Context, arg InsertCurrencyParams) error {
	_, err := q.db.Exec(ctx, insertCurrency, arg.Code, arg.Name)
	return err
}

const saveCurrencyRate = `-- name: SaveCurrencyRate :exec
INSERT INTO currency_rates (currency_code, rate, rate_date)
VALUES ($1, $2, $3)
ON CONFLICT (currency_code, rate_date) 
DO UPDATE SET rate = EXCLUDED.rate
`

type SaveCurrencyRateParams struct {
	CurrencyCode string
	Rate         pgtype.Numeric
	RateDate     time.Time
}

func (q *Queries) SaveCurrencyRate(ctx context.Context, arg SaveCurrencyRateParams) error {
	_, err := q.db.Exec(ctx, saveCurrencyRate, arg.CurrencyCode, arg.Rate, arg.RateDate)
	return err
}
