// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRate = `-- name: CreateRate :one
INSERT INTO currency_rates (currency_code, rate, rate_date, source, change_percentage)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (currency_code, rate_date) DO UPDATE SET
  rate = EXCLUDED.rate,
  source = EXCLUDED.source,
  change_percentage = EXCLUDED.change_percentage
RETURNING id, currency_code, rate, rate_date, source, change_percentage
`

type CreateRateParams struct {
	CurrencyCode     string         `json:"currency_code"`
	Rate             pgtype.Numeric `json:"rate"`
	RateDate         pgtype.Date    `json:"rate_date"`
	Source           string         `json:"source"`
	ChangePercentage pgtype.Numeric `json:"change_percentage"`
}

func (q *Queries) CreateRate(ctx context.Context, arg CreateRateParams) (CurrencyRate, error) {
	row := q.db.QueryRow(ctx, createRate,
		arg.CurrencyCode,
		arg.Rate,
		arg.RateDate,
		arg.Source,
		arg.ChangePercentage,
	)
	var i CurrencyRate
	err := row.Scan(
		&i.ID,
		&i.CurrencyCode,
		&i.Rate,
		&i.RateDate,
		&i.Source,
		&i.ChangePercentage,
	)
	return i, err
}

const getLatestRates = `-- name: GetLatestRates :many
SELECT DISTINCT ON (currency_code) id, currency_code, rate, rate_date, source, change_percentage
FROM currency_rates
ORDER BY currency_code, rate_date DESC
`

func (q *Queries) GetLatestRates(ctx context.Context) ([]CurrencyRate, error) {
	rows, err := q.db.Query(ctx, getLatestRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrencyRate{}
	for rows.Next() {
		var i CurrencyRate
		if err := rows.Scan(
			&i.ID,
			&i.CurrencyCode,
			&i.Rate,
			&i.RateDate,
			&i.Source,
			&i.ChangePercentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRateHistory = `-- name: GetRateHistory :many
SELECT rate, rate_date
FROM currency_rates
WHERE currency_code = $1 AND rate_date >= $2
ORDER BY rate_date ASC
`

type GetRateHistoryParams struct {
	CurrencyCode string      `json:"currency_code"`
	RateDate     pgtype.Date `json:"rate_date"`
}

type GetRateHistoryRow struct {
	Rate     pgtype.Numeric `json:"rate"`
	RateDate pgtype.Date    `json:"rate_date"`
}

func (q *Queries) GetRateHistory(ctx context.Context, arg GetRateHistoryParams) ([]GetRateHistoryRow, error) {
	rows, err := q.db.Query(ctx, getRateHistory, arg.CurrencyCode, arg.RateDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRateHistoryRow{}
	for rows.Next() {
		var i GetRateHistoryRow
		if err := rows.Scan(&i.Rate, &i.RateDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
